# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

class SumFibonacci

  def sum_even_numbers
    self.send(:even_numbers_only).reduce(:+)
  end

  private

    def create_sequence
      sequence = [1, 2]

      while (sequence[-1] + sequence[-2]) < 4000000
        calculate_next_term(sequence)
      end

      sequence
    end

    def calculate_next_term(sequence)
      sequence << (sequence[-1] + sequence[-2])
    end

    def even_numbers_only
      self.send(:create_sequence).keep_if { |n| n % 2 == 0 }
    end

end
